import type { ProjectCatalogEntry } from "@/features/portfolio/content/types";
import type { ProjectSlug } from "@/features/portfolio/types/projectTypes";

export const projectManifest = {
    portfolio: {
        slug: "portfolio",
        order: 14,
        status: "private",
        stack: [
            "Next.js 16",
            "TypeScript",
            "Zustand",
            "i18next",
            "Tailwind CSS",
            "Supabase",
            "TanStack Query",
            "Playwright",
            "Vitest",
            "Vercel",
        ],
        resumeStack: ["Next.js", "TypeScript", "Zustand", "Tailwind CSS"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
    optigen: {
        slug: "optigen",
        order: 12,
        status: "private",
        stack: [
            "Next.js 16",
            "TypeScript",
            "TanStack Query",
            "Zustand",
            "Zod",
            "shadcn/ui",
            "Tailwind CSS",
            "Storybook",
        ],
        resumeStack: ["Next.js", "TypeScript", "TanStack Query", "Zustand"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
    mcp: {
        slug: "mcp",
        order: 20,
        status: "private",
        stack: [
            "Node.js",
            "TypeScript",
            "MCP SDK",
            "Express.js",
            "Zod",
            "FFmpeg",
            "Pino",
        ],
        resumeStack: ["Node.js", "TypeScript", "MCP SDK", "Express.js"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
    "voice-gateway": {
        slug: "voice-gateway",
        order: 21,
        status: "private",
        stack: [
            "Node.js",
            "TypeScript",
            "WebSocket",
            "Zod",
            "Axios",
            "Vitest",
            "Pino",
        ],
        resumeStack: ["Node.js", "TypeScript", "WebSocket", "Pino"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
    kepco: {
        slug: "kepco",
        order: 10,
        status: "private",
        stack: [
            "React 19",
            "TypeScript",
            "Vite",
            "TanStack Query",
            "Zustand",
            "Tailwind CSS",
            "Axios",
            "Playwright",
        ],
        resumeStack: ["React 19", "TypeScript", "TanStack Query", "Zustand"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
    wchms: {
        slug: "wchms",
        order: 30,
        status: "private",
        stack: ["Next.js", "TypeScript", "MySQL", "OpenAI"],
        resumeStack: ["Next.js", "TypeScript", "MySQL", "OpenAI"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
    flare: {
        slug: "flare",
        order: 40,
        status: "private",
        stack: [
            "Next.js 15",
            "TypeScript",
            "Tailwind CSS",
            "PostgreSQL",
            "Drizzle ORM",
            "OpenAI API",
            "Google Maps",
            "Firebase Cloud Messaging",
            "PWA",
        ],
        resumeStack: ["Next.js", "TypeScript", "PostgreSQL", "OpenAI"],
        icon: "/icons/optimized/document.png",
        links: {},
        media: [],
    },
} satisfies Record<ProjectSlug, ProjectCatalogEntry>;
